### PR TITLE
[FEATURE] Provide rules to migrate EXT:vhs viewhelpers

### PR DESCRIPTION
**Pull request by kitzberger**
* v:extension.path.relative -> f:uri.resource
* v:format.json.encode -> f:format.json
* v:media.image -> f:media.image
* v:uri.image -> f:uri.image
* v:l -> f:translate
* v:variable.set -> f:variable
* v:or -> inline ternary operator

t.b.c.

### CODE REVIEW

**Comment by helsner** [comment]
Nice draft, a note though:
The `v:variable.set -> f:variable` change could cause issues, when used with multi dimensional
so `v:variable.set name="foo.bar"` won't work with `f:variable name="foo.bar"` from my experience

**Comment by sabbelasichon** [comment]
@kitzberger Nice. What we will also need are tests. Could you provide them?

**Comment by kitzberger** [comment]
> @kitzberger Nice. What we will also need are tests. Could you provide them?

@sabbelasichon, like this? Any suggestions? I know, one is failing. I need to figure out how to migrate single viewhelper properties.

**Comment by kitzberger** [comment]
> Nice draft, a note though: The `v:variable.set -> f:variable` change could cause issues, when used with multi dimensional so `v:variable.set name="foo.bar"` won't work with `f:variable name="foo.bar"` from my experience

@helsner, good point. Is there a way of migrating the code and print some warning in such a case? Or is that counter-productive since nobody every reads them anyways?

**Comment by helsner** [comment]
I would say there is no proper way of migration as the logic behind the car cannot be further checked (especially in HTML).
A warning should be possible and the prevention of changing the view helper call in case there is a dot within the name
As we don't change the code then, it should already be good, in case the warning is ignored we don't destroy functionality and I cannot help people that ignore our notice 🤷

**Comment by kitzberger** [comment]
Do you know of any examples where a warning is being output? Thanks for your input :-)

**Comment by helsner** [comment]
> Do you know of any examples where a warning is being output? Thanks for your input :-)

simply look for `rectorOutputStyle` in existing rules.
It's basically used via constructor and `...->warning()` call most of the times

**Comment by kitzberger** [comment]
@helsner, thanks for the hint!

I've now added a more strict pattern to detect the simple cases like: `v:variable.set name="xx"` and migrate only those automatically. Any left occurrences of v:variable.set I keep untouched and print a warning instead.

**Comment by helsner** [comment]
@kitzberger nice, but i would point out to why the change is not made as well, as this might not be known (i found that out the hard way 😂 )

**Comment by helsner** [comment]
This still looks great, but i just checked and noticed that we have some TODO's left

**Comment by mehdichaouch** [comment]
> This still looks great, but i just checked and noticed that we have some TODO's left

Nice PR, do you know when it'll be ready to merge?

Thanks,

**Comment by sabbelasichon** [comment]
@helsner What kind of TODO´s are left here?

**Comment by helsner** [comment]
> @helsner What kind of TODO´s are left here?

Those marked in the code I guess
Maybe we can still merge and they will be added afterwards
But usually we migrate fully because it would cause too much frustration not handling attributes etc

**Comment by sabbelasichon** [comment]
@helsner If you like you can merge it. I am not using VHS anyways ;-)

**Comment by helsner** [comment]
@kitzberger what about you phillipp?
are you ready to merge?

**Pull request merged**
