### PR TITLE
Migrate AbstractRectorWithConfigTestCase to use SmartFileInfo and  and typo3_rectors.yaml to PHP

### PR DESCRIPTION
**Pull request by tmotyl**
Depends on https://github.com/sabbelasichon/typo3-rector/pull/1472 which shoud be merged first 

The PR fixes issues like:

```
Rector\Core\Exception\ShouldNotHappenException: Class "" in "getRectorClass()" method must be type of "Rector\Core\Contract\Rector\PhpRectorInterface"

or 

1) Ssch\TYPO3Rector\Tests\Rector\Annotation\AnnotationTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Argument 1 passed to PHPStan\Type\ObjectType::__construct() must be of the type string, int given, called in ...

or 
1) Ssch\TYPO3Rector\Tests\Rector\Annotation\AnnotationTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Argument 2 passed to Nette\Utils\Strings::startsWith() must be of the type string, int given, called in rector/typo3-rector/vendor/rector/rector/rules/naming/src/NamespaceMatcher.php on line 21

or

Symfony\Component\Config\Exception\LoaderLoadException: Cannot use values of type "Rector\Renaming\ValueObject\MethodCallRename" in service configuration files in /rector/typo3-rector/config/typo3-95.php (which is being imported from "rector/typo3-rector/tests/config/typo3_rectors.php").

```
 when running typo3-rector unit tests.

However when typo3-rector is installed with lower dependencies tests are failing with:
```
Error: Call to undefined function Symfony\Component\DependencyInjection\Loader\Configurator\inline_service()
```
I think the inline_service function was provided in Symfony 5.1, thus composer requirements of rector are wrong (allowing symfony 4.x too).

When I've installed Symfony 5.1 packages, I've got following error with phpunit:

```
1) Ssch\TYPO3Rector\Tests\Rector\Annotation\AnnotationTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Argument 2 passed to Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockManipulator::replaceAnnotationInNode() must be an instance of Rector\Renaming\ValueObject\RenamedAnnotationInType, string given, called in /rector/typo3-rector/src/Rector/Annotation/InjectAnnotationRector.php on line 71

2) Ssch\TYPO3Rector\Tests\Rector\Backend\Utility\BackendUtilityEditOnClickRectorTest::test with data set #0 ('...hp.inc')
TypeError: Argument 1 passed to Ssch\TYPO3Rector\Tests\Rector\Backend\Utility\BackendUtilityEditOnClickRectorTest::test() must be an instance of Symplify\SmartFileSystem\SmartFileInfo, string given, called in rector/typo3-rector/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1533

```
But at last, some tests are green now  :)

### CODE REVIEW

**Comment by tmotyl** [comment]
@TomasVotruba based on your PR's I've tried to make unit tests green. As you see I managed to make one step forward, but I got stuck with "cannot use values of type "Rector\Renaming\ValueObject\MethodCallRename" in service configuration files in /rector/typo3-rector/config/typo3-95.php" 
Can you give any hints how to solve it, or fix it yourself?

Can you also confirm the issue with wrong `symfony/dependency-injection` dependency in rector?

**Comment by tmotyl** [comment]
I've managed to fix MethodCallRename and some other issues, but now I'm stuck at 
```
1) Ssch\TYPO3Rector\Tests\Rector\Annotation\AnnotationTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Argument 2 passed to Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockManipulator::replaceAnnotationInNode() must be an instance of Rector\Renaming\ValueObject\RenamedAnnotationInType, string given, called in /rector/typo3-rector/src/Rector/Annotation/InjectAnnotationRector.php on line 71

2) Ssch\TYPO3Rector\Tests\Rector\Backend\Utility\BackendUtilityEditOnClickRectorTest::test with data set #0 ('...hp.inc')
TypeError: Argument 1 passed to Ssch\TYPO3Rector\Tests\Rector\Backend\Utility\BackendUtilityEditOnClickRectorTest::test() must be an instance of Symplify\SmartFileSystem\SmartFileInfo, string given, called in rector/typo3-rector/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1533
```

any hints welcome :)

**Comment by sabbelasichon** [comment]
@tmotyl I am investigating and will fix the errors.

**Comment by TomasVotruba** [comment]
@tmotyl  I haven't got that far :D these errors are some detailed change I'm not aware of.
 
@sabbelasichon Let me know if you get stuck. I can handle this

**Comment by tmotyl** [comment]
@TomasVotruba can you confirm the issue with "composer update --prefer-lowest" and rector?

**Comment by sabbelasichon** [comment]
@tmotyl I fixed the tests with custom PR #1474

**Comment by TomasVotruba** [comment]
@tmotyl That usually means that version in `composer.json` is too low.
I've seen it here.

This usually fixes it:

```diff
-"rector/rector": "^0.8",
+"rector/rector": "^0.8.6",
```

I tend to use latest version, as it's the one with most fixes (usually :)) 
The latest version can be found here: https://packagist.org/packages/rector/rector

**Comment by sabbelasichon** [comment]
@TomasVotruba All tests are passed. Thank you very much for your amazing work.

**Comment by TomasVotruba** [comment]
Wow, that was faster than I expected :+1: 

Glad to help!

In case of troubles just ping me here on GitHub. I'll check it

**Comment by tmotyl** [comment]
@TomasVotruba the most recent rector allow `symfony/dependency-injection: ^4.4.8|^5.0.6` and AFAIK `Symfony\Component\DependencyInjection\Loader\Configurator\inline_service()` is available only since 5.1 (before the method has different name if I read it correctly the 5.1 changelog: https://github.com/symfony/dependency-injection/blob/34eefcfff4ff4e628f6571f4460b0825e5e7e47b/CHANGELOG.md#510)

**Comment by tmotyl** [comment]
@TomasVotruba I've created an issue for this on rector side (I've confirmed the issue by running rector unit tests with --prefer-lowest) https://github.com/rectorphp/rector/issues/4218

**Comment by TomasVotruba** [comment]
@tmotyl Thanks :+1:

**Pull request closed without merging**
