### PR TITLE
[WIP] [TASK] Add Docker and CI documentation and templates

### PR DESCRIPTION
**Pull request by t3easy**
Resolves: #1920

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@t3easy Really cool. Tried it locally and it works like a charm.

**Comment by sabbelasichon** [comment]
@t3easy Could you add also the link from the README.md to your .md files.

**Comment by sabbelasichon** [comment]
@t3easy I would like to merge this one here. We can still improve the documentation after real usage.

**Comment by maddy2101** [comment]
merge it! This reads very good.

**Comment by t3easy** [comment]
@maddy2101 @sabbelasichon Sorry im quite busy and hope you tested all... It was marked as wip because i couldn't test the GitLab workflow :)

**Pull request merged**
