### PR TITLE
[FEAT] Replace TSFE->ATagParams calls

### PR DESCRIPTION
**Pull request by helsner**
Relates: #2670

### CODE REVIEW

**Comment by helsner** [comment]
This was hell itself IMHO.. the array and property switching was pretty hard and i don't even know how i got it.
Also there was no example in another rule, so i tried to copy it from various places 

BE AWARE: this does only solve one part of the RST-file, as the method call is not changed - should i do that as well in another rule? (would do so, but ask before wasting time)

**Comment by sabbelasichon** [comment]
@helsner I would create another rule for the second part of the RST-File. Really well solved. Nothing to add.

**Comment by helsner** [comment]
OK will do so tomorrow

**Comment by helsner** [comment]
I would merge myself this time if everything is clear hihi

**Pull request merged**
