### PR TITLE
[TASK] Upgrade to Rector 1.0

### PR DESCRIPTION
**Pull request by sabbelasichon**

### CODE REVIEW

**Review by helsner — APPROVED** [review]
Hooray

**Comment by wolffc** [comment]
Hooray 🎉🎉🎉🎉!

**Comment by oliverklee** [comment]
Hooray!

**Comment by kevin-appelt** [comment]
And number 5: Hooray 🥳 🎉

**Comment by simonschaufi** [comment]
Tadaaaa  🎉

**Comment by Wipster** [comment]
🔥🔥🔥

**Comment by derhansen** [comment]
Post-Hooray 👍

**Pull request merged**
