### PR TITLE
[TASK] Use UriBuilder instead of BackendUtility::getModuleUrl

### PR DESCRIPTION
**Pull request by MK-42**
I'm not sure how to migrate the 'buildUriFromModule` deprecation properly.

Happy to get feedback, first real rector I wrote.

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@MK-42 Thanks for your PR. Amazing to see contributions from different people. Love it.

**Comment by tmotyl** [comment]
this PR is related to issue: https://github.com/sabbelasichon/typo3-rector/issues/1040

**Comment by tmotyl** [comment]
@MK-42 due to migration to newest Rector version, the config has changed from yaml to php.
Would you be able to migrate the PR to new config?
Btw, feel invited to join #ext-typo3-rector channel on TYPO3 slack

**Comment by tmotyl** [comment]
@MK-42 looks good, but there are just some minor coding style issues: https://github.com/sabbelasichon/typo3-rector/pull/1393/checks?check_run_id=1166040672

**Comment by MK-42** [comment]
this failure now looks unrelated to these changes?

**Review by sabbelasichon — APPROVED** [review]

**Comment by tmotyl** [comment]
Yey! Congratulations for the contribution @MK-42 !

**Pull request merged**
