### PR TITLE
[BUGFIX] Use absolute file path without project prefix

### PR DESCRIPTION
**Pull request by simonschaufi**
Resolves: #4291

### CODE REVIEW

**Comment by Kanti** [comment]
This breaks https://github.com/sabbelasichon/typo3-rector/pull/4277 again.
can we revert this change or find a Solution for this problem?

**Comment by simonschaufi** [comment]
As you can see, this is actually a fix for another issue. I wonder why you define the path in the cli and not in rector config?

**Comment by Kanti** [comment]
For normal rector execution, I don't need to specify the path in the rector config.
I did not think that I need to define in what path the root of the project is.

I searched the rector.php examples for both rector and typo3-rector and could not find a way to define the path.
How would I define the path?

**Comment by simonschaufi** [comment]
You don't specify the root path but only the paths in which rector should run, see:
https://github.com/sabbelasichon/typo3-rector/blob/main/templates/rector.php.dist#L17
Rector will the figure out the path by itself.

**Comment by Kanti** [comment]
This is a really good piece of info :)

We have a helper in the paths and give all files individually to rector:
````php
$rectorConfig->paths(
    array_filter(explode("\n", (string)shell_exec("git ls-files | xargs ls -d 2>/dev/null | grep -E '\.(php)$'")))
);
````

It works as you said if I just set the path a directory.

````php
$rectorConfig->paths(
    [__DIR__ . '/src/']
);
````

But this is not nice if we only have the option to define paths if we want to use typo3-rector.

This also applies to the rector command if you add a filename as a parameter.
e.g:
`rector process src/extension/test_extension/ext_tables.php`.

Then I still get the error `Unable to create directory at /src/extensions/test_extension/Configuration/TCA/Overrides. mkdir(): Permission denied'. This is also a problem if I only set the directory in the rector config.

@simonschaufi can we have the `getcwd()` back in the code? or should we find another solution?

**Comment by simonschaufi** [comment]
If getcwd breaks the code, then we should find another solution or a real fix that doesn't break but I'm not motivated to spend time in this right now as defining the paths works great.

**Comment by Kanti** [comment]
I have written a summary in the issue #4301
I will try to find a solution without breaking the usage of the CLI from a different Project path.

**Pull request merged**
