### PR TITLE
Bump to PHP 7.4 and 8.0 syntax and fix infinite loop rules

### PR DESCRIPTION
**Pull request by TomasVotruba**
See https://github.com/rectorphp/rector/issues/6576

### CODE REVIEW

**Comment by sabbelasichon** [comment]
Ready to merge? Looks good to me

**Comment by TomasVotruba** [comment]
CS is stuck on CI for some reason :/ locally is fine

Ready to merge otherwise :+1:

**Comment by TomasVotruba** [comment]
Ok, locally it's broken too, WIP...

**Comment by TomasVotruba** [comment]
Ready to go :+1:

**Comment by TomasVotruba** [comment]
I've merged the PR to see results. Could you tag a new version please?

**Comment by sabbelasichon** [comment]
I have asked @helsner He is doing it.I am not able to do it on my phone

**Comment by TomasVotruba** [comment]
Thank you @sabbelasichon and @helsner :+1:

**Pull request merged**
