### PR TITLE
[TASK] Align with new TYPO3 documentation standards

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Hi Sebastian,

this PR is a suggestion to align your package documentation with the recently introduced [TYPO3 documentation standards](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html).

I mainly reworked some content, moved your documentation TOC to /docs, added some badges in README and additional sources (TER, repository and docs.typo3.org) in composer.json.

Greetings, Alex

Relates: TYPO3-Documentation/T3DocTeam#182
Relates: TYPO3-Documentation/T3DocTeam#185

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@alexander-nitsche Thank you. 
@helsner What do you think? You are the master of the documentation. Feel free to merge if you like.

**Comment by helsner** [comment]
thanks for your effort - looks good and i'm fine with all of that but one thing:
You removed the sentence where it says that this repo is only for dev and not to clone.
In the past we often had issues with people trying typo3-rector directly and not using rector/rector, so i would like to keep that somehow.
This won't prevent people 100%, but at least we can say it's in the docs :D 
Whats you opinion on that @sabbelasichon ?

**Comment by alexander-nitsche** [comment]
Sure, adjust to your likes.

My explanation for the removal: I combined this hint with the mentioning of the parent Rector project:
> It **extends** the [Rector](https://github.com/rectorphp/rector) project, which aims to provide instant upgrades and instant refactoring for any PHP code (5.3+).

I would suggest to extend this sentence if you still want to be more precise on the Rector dependency here.

**Comment by helsner** [comment]
Ah ok, i'll think about something, but other than that thank you very much for your big change!

**Comment by sabbelasichon** [comment]
@alexander-nitsche @helsner Thanks both of you.

**Pull request merged**
