### PR TITLE
[BUGFIX] Resolve ReturnType 'void' along with DocComment

### PR DESCRIPTION
**Pull request by helsner**
Relates: #3023

### CODE REVIEW

**Review by simonschaufi — APPROVED** [review]

**Comment by simonschaufi** [comment]
@helsner I'm fine with the change itself but I'm sad that phpstan is broken again :cry: 

I would prefer to first fix the phpstan issue, then rebase this patch to have everything green again.

**Comment by helsner** [comment]
Yeah, I'm currently on another rule with the same issue after composer update
Seems like something got updated and now the whole chain breaks
I'm already looking but did not find anything yet

**Comment by helsner** [comment]
it breaks with "symplify/phpstan-rules": "10.3.1",
10.3.0 works so yeah

**Comment by simonschaufi** [comment]
I'm therefore happy with making the version sticky because dependencies could easily crash our pipeline anytime, which is really annoying.

**Comment by helsner** [comment]
I will do that then.

**Pull request merged**
