### PR TITLE
[TASK] Update rector to latest 0.17 version

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by simonschaufi** [comment]
Breaking really hard because of:

-  https://github.com/rectorphp/rector-src/pull/4190

**Comment by mgerdes-atl** [comment]
Hi @simonschaufi ,

any news on the hardcoded dependency of rector/rector 0.17.0 ?
Any updates planned so far?

Regards 
Markus

**Comment by simonschaufi** [comment]
Feel free to give it a try but since there is no clear migration path for rector, it is a huge task. Some things are also removed that we use. I want to focus more on creating rules than updating rector which is more fun 🥳

**Comment by sabbelasichon** [comment]
I am going to close this issue. We should do the migration in baby steps.

**Comment by simonschaufi** [comment]
@sabbelasichon Upgrading rector 0.17.0 to 0.17.13 is a baby step for me but ok...

**Comment by sabbelasichon** [comment]
No, it is not

**Comment by simonschaufi** [comment]
It really sucks that rector is just throwing things away without giving alternatives and doesn't explain how to migrate code...

**Comment by sabbelasichon** [comment]
I know. I have been there. It sucks. But what is the alternative? Let's focus on the most important things.

**Pull request closed without merging**
