### PR TITLE
TASK: Return multiple nodes instead of using NodesToAddCollector

### PR DESCRIPTION
**Pull request by sabbelasichon**
Relates: #3982

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@simonschaufi We should either remove some complex rarely used rule which uses the NodesToAddCollector or refactor them. This can be quite cumbersome but we should move forward.

**Comment by simonschaufi** [comment]
@sabbelasichon The title of the issue doesn't make it clear that it also removes some rules. Why did you actually remove them?

**Comment by sabbelasichon** [comment]
Too old. Never used them. Never seen them in the wild tbh. Drop complexity. Focus on important thingd

**Comment by simonschaufi** [comment]
ok but then we should also mark the commits somehow because we also don't really follow semver at the moment.

**Comment by sabbelasichon** [comment]
I don't really care. Being pragmatic in that regard

**Pull request merged**
