### PR TITLE
[TASK] Replace yaml configuration syntax with php syntax

### PR DESCRIPTION
**Pull request by cschnell**
Rector has deprecated the yaml syntax and will remove it in 0.8.0
The Yaml Files have been converted to php configuration syntax and
the calls for RenameNamespaceRector and RenameMethodRector have been
adjusted according to rector.

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@cschnell Thank you very much. Due to vacations and a lot of work afterwards i could not respond earlier. I will have a look into it soon.

**Comment by Cabag** [comment]
Thanks for your reply. Unfortunately I could not get the unit tests running in this PR. Seems to be a bit more work required.

**Comment by tmotyl** [comment]
migrated in https://github.com/sabbelasichon/typo3-rector/commit/c3c28747ef0c598f925f91d214517bee490ce14f and https://github.com/sabbelasichon/typo3-rector/pull/1473

**Comment by sabbelasichon** [comment]
@cschnell Thanks. We solved this issue by another PR #1471. Thanks a lot anyways. Every PR is welcome.

**Pull request closed without merging**
