### PR TITLE
[WIP] config: remove local phpstan config reference

### PR DESCRIPTION
**Pull request by TomasVotruba**
It would cause trouble like these 
https://github.com/rectorphp/rector-src/pull/46/checks?check_run_id=2592322406#step:5:15

### CODE REVIEW

**Comment by sabbelasichon** [comment]
The stubs should be added to the composer.json classmap like here: https://github.com/rectorphp/rector-src/blob/main/composer.json#L88

**Comment by TomasVotruba** [comment]
That's the best. Yes :+1: 
Just in `autoload-dev`, so it's local for your project

**Comment by sabbelasichon** [comment]
Locally everything went fine. Why are the stubs not found and static reflection is not working in the ci?

**Comment by sabbelasichon** [comment]
Ok. I am gonna fix it. I have seen what you have done for nette.

**Pull request merged**
