### PR TITLE
Remove rule QueryLogicalOrAndLogicalAndToArrayParameterRector #3071

### PR DESCRIPTION
**Pull request by froemken**
Resolves: #3071

### CODE REVIEW

**Comment by simonschaufi** [comment]
What is your intention, why was this rule removed?

**Comment by helsner** [comment]
Resolves: #3071

**Comment by froemken** [comment]
@simonschaufi Sorry, I have forgotten to add the Issue #3071 in my commit message. I have described it there on detail. Thank you @helsner to put this PR into relation

**Review by simonschaufi — APPROVED** [review]

**Review by helsner — CHANGES_REQUESTED** [review]
I would decline this change.
It might seem not logical to you now, but when upgrading the core to v9 this is a necessary change.
Within v10 the method changed into multiple arguments, but in v9 LTS it is not, thus making this rule fully correct in its place.
As there is no change until now it is not wrong to have this active, even though it might irritate one.
In case the TODO segment within the logicalAnd will be integrated there will be a new changelog entry which then will turn into a rule of us.
But for the sake of the whole chain to work this is fitting and necessary

**Comment by simonschaufi** [comment]
@helsner thanks for your detailed code review

**Comment by simonschaufi** [comment]
Well but if it's not an array, all passed arguments are used: https://github.com/TYPO3/typo3/blob/9.5/typo3/sysext/extbase/Classes/Persistence/Generic/Query.php#L417 but still, the IDE will complain about wrong number of arguments, so passing an array is "more correct".

**Comment by helsner** [comment]
Yeah we could do that or exclude the rule within the v9 config.
But in general i would guess this does not break anything and in case this method will change in the future we will have a new rule to rewrite or we can drop it then

**Comment by simonschaufi** [comment]
One can always exclude single rules with:

```php
$rectorConfig->services()->remove(QueryLogicalOrAndLogicalAndToArrayParameterRector::class);
```

**Comment by sabbelasichon** [comment]
The rule confuses at least some people. So does other rules. I would vote for dropping it. Let's focus on the important ones

**Comment by froemken** [comment]
Why you have close this PR? Because the IDE complains about wrong type?!
"this does not break anything" -> that's correct, but it touches code which does not have to be updated. I still prefer to remove that rule.

**Comment by helsner** [comment]
In general it does not matter if the rule is applied or not for a proper update to a current TYPO3 release.
It does though for specific updates to v9.
So the decision is if we see this as use case as the version is relatively old.

For me it would also be ok to drop the rule with that perspective.

**Comment by simonschaufi** [comment]
@helsner Does it really matter for v9? The code in v8.7 looks exactly the same: https://github.com/TYPO3/typo3/blob/TYPO3_8-7/typo3/sysext/extbase/Classes/Persistence/Generic/Query.php#L404

**Comment by helsner** [comment]
we should take the original issue into perspective #2462
The issue seems to be a combination with other tools that want to cleanup the superfluous arguments.
So the reason for the existence if the rule is to prevent harm by deleting the arguments wrongfully/before the actual migration to a newer TYPO3 version

**Comment by simonschaufi** [comment]
Ok, the problem is if you additionally use https://github.com/rectorphp/rector-src/blob/main/rules/Php71/Rector/FuncCall/RemoveExtraParametersRector.php.

I still vote for: keep our rule and let the user exclude it.

**Review by simonschaufi — CHANGES_REQUESTED** [review]
let's keep this rule

**Comment by helsner** [comment]
regarding the reason for the existence of the rule i figured out. i support to keep it.
I prefer to prevent issues caused by rector

**Comment by helsner** [comment]
lolz - for documentation:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96044-HardenMethodSignatureOfLogicalAndAndLogicalOr.html

**Pull request closed without merging**
