### PR TITLE
[Dep] Update PHP requirement to PHP 8.1

### PR DESCRIPTION
**Pull request by samsonasik**
@sabbelasichon rector is updating requirement to php 8.1, I think this should be updated to php 8.1 as well.

@TomasVotruba currently, as rector require `ssch/typo3-rector` that require `helmich/typo3-typoscript-parser`, the downgrade on rector got deprecation warning, ref https://github.com/rectorphp/rector-src/runs/4427367192?check_suite_focus=true#step:9:431

```bash
[▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  41%PHP Deprecated:  Return type of Helmich\TypoScriptParser\Parser\TokenStream::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/rector-src/rector-src/vendor/helmich/typo3-typoscript-parser/src/Parser/TokenStream.php on line 96
Deprecated: Return type of Helmich\TypoScriptParser\Parser\TokenStream::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/rector-src/rector-src/vendor/helmich/typo3-typoscript-parser/src/Parser/TokenStream.php on line 96
PHP Deprecated:  Return type of Helmich\TypoScriptParser\Parser\TokenStream::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/rector-src/rector-src/vendor/helmich/typo3-typoscript-parser/src/Parser/TokenStream.php on line 105
Deprecated: Return type of Helmich\TypoScriptParser\Parser\TokenStream::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/rector-src/rector-src/vendor/helmich/typo3-typoscript-parser/src/Parser/TokenStream.php on line 105
```

I created another PR to https://github.com/martin-helmich/typo3-typoscript-parser/pull/76 for it.

### CODE REVIEW

**Comment by samsonasik** [comment]
it seems there is another notice:

```bash
PHP Deprecated:  Return type of Apache_Solr_Document::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/typo3-rector/typo3-rector/stubs/SolrPhpClient/Apache_Solr_Document.php on line 120
```

it shown when running phpunit.

**Comment by samsonasik** [comment]
I added #[\ReturnTypeWillChange] to stub apache solr document

**Comment by samsonasik** [comment]
@TomasVotruba it seems we can apply change to `#[\ReturnTypeWillChange]` `helmich/typo3-typoscript-parser` via vendor patches? that possibly will require `rector-src` to patches as `helmich/typo3-typoscript-parser` well.

The current Update vendor patches files to vendor-patches repository https://raw.githubusercontent.com/rectorphp/vendor-patches path not yet working as it seems still pointed to `patches` directory, probably due to requirement dependencies, as I commented at https://github.com/rectorphp/rector-src/pull/1377#issuecomment-985766379

**Comment by samsonasik** [comment]
I updated vendor-patches repository to include `helmich/typo3-typoscript-parser` so we can have it covered

https://github.com/rectorphp/vendor-patches/blob/master/helmich-typo3-typoscript-parser-parser-tokenstream-php.patch

Note: the `patches` directory still needed for resolve `danielstjules/stringy` and `symfony/dependency-injection` as all packages needs to be updated to url based first and tagged ref https://github.com/rectorphp/rector-src/pull/1377#issuecomment-987521301

**Comment by samsonasik** [comment]
All checks have passed 🎉 @sabbelasichon @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
@samsonasik Thank you for your work 👍 

@sabbelasichon As this is quite a jump, I want to confirm with you first :) Could you check if that's ok for you and review/merge?

**Comment by sabbelasichon** [comment]
Yes, will do.

**Comment by sabbelasichon** [comment]
@samsonasik Thanks a lot for your work.

**Comment by samsonasik** [comment]
I removed the patches directory as all rector-* packages pointed to vendor patch URL.

**Comment by samsonasik** [comment]
I  updated to use enable-patching config

**Pull request merged**
