### PR TITLE
[FEATURE] Enable EXTKEY to be replaced in sys_template

### PR DESCRIPTION
**Pull request by helsner**
Refs #2162

### CODE REVIEW

**Comment by sabbelasichon** [comment]
Thanks. Maybe it can be useful for every file under Configuration/TCA/Overrides. Right? Do you think it is possible to reliable fix that?

**Comment by helsner** [comment]
I was thinking about that, too.
Basically i would guess the replace makes sense in every file, not limited to TCA.
I could think of usages where you have a BE module that requires custom JS which is then used via extPath..
A more basic usage would be for iconfiles in normal TCA config.

So we actually could think about overall dropping the limitation by filename - i dunno if this would cause any trouble though.
We might ask others on this

**Comment by sabbelasichon** [comment]
It is only obligatory be only in ext_emconf.php. At least for extensions in the TER

**Comment by helsner** [comment]
Then i guess we should actually think about dropping the file limitation
What do you think?
We could address this in the channel for more input

**Comment by sabbelasichon** [comment]
Just take the file ext_emconf.php into account and do not substitute it there. On all other files you can safely substitute it. The only thing is if someone use this variable in his custom code. Should rarely be the case, but never say never.

**Pull request merged**
