### PR TITLE
feat: replace TYPO3 inject annotations with setter methods

### PR DESCRIPTION
**Pull request by helsner**
Resolves: #1780

### CODE REVIEW

**Comment by helsner** [comment]
I'm currently having issues with my local debugger so i cannot look further into why the replacement does not work

**Comment by sabbelasichon** [comment]
@helsner will have a look now

**Comment by helsner** [comment]
Don't worry
We can do that after Christmas as well 😅
At least I will get back on rector then

**Comment by sabbelasichon** [comment]
@helsner What do you think, is it ready to ship?

**Pull request merged**
