### PR TITLE
Make PHPStan smarter on getNodeTypes()

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to merge :+1:

**Comment by TomasVotruba** [comment]
Failing "Build Scoped TYPO3 Rector" is expected - due to fork without access

> fatal: could not read Username for 'github.com': No such device or address"

**Comment by sabbelasichon** [comment]
@TomasVotruba What about the Rector fix? I am still new to this syntax. Is allowed to work without the FQN?

**Comment by TomasVotruba** [comment]
Ups, I missed that. I'm so used to Rector commit these changes to PR for me :) 

Will fix.

**Pull request merged**
