### PR TITLE
[BUGFIX] Add type as namespace

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by simonschaufi** [comment]
I have overlooked that the file is put in a subdirectory depending on the rector type, but then the namespace doesn't match to the folder. Of course, it would be better to have all rectors in the same folder, but then I would need to do some more magic and remove the "type directory". I also saw that TypoScript rectors are also put into `src/FileProcessor/TypoScript/Rector/v12/v0` but then we need some kind of mapping where to put each rector type.

**Comment by TomasVotruba** [comment]
Hi, this looks good to me.

Could you rebase on `main`?

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
👍

**Comment by simonschaufi** [comment]
@TomasVotruba please use rebase mode to merge, to get a nice and clean git history without any merge commits. Thanx.

**Comment by TomasVotruba** [comment]
I take the default one and prefer it.

**Pull request merged**
