### PR TITLE
Upgrade to Rector 2.0 with PHPStan 2 and PHPParser 5

### PR DESCRIPTION
**Pull request by samsonasik**
Rector is upgrading to PHPStan 2 and PHPParser 5 at PR:

- https://github.com/rectorphp/rector-src/pull/6431

this PR upgrade for compatiblity syntax.

Fixes: #4247

### CODE REVIEW

**Comment by samsonasik** [comment]
Unit test green 🎉 https://github.com/sabbelasichon/typo3-rector/actions/runs/11950281307/job/33311437868?pr=4450

Next todo is fix phpstan notice

**Comment by sabbelasichon** [comment]
@samsonasik Thank you very much. This is amazing.

**Comment by samsonasik** [comment]
Ready when Rector 2.0 released, rector/rector can be updated to:

```diff
- "rector/rector": "dev-main as 1.2.10",
+ "rector/rector": "~2.0.0",
```

**Comment by simonschaufi** [comment]
Wow, you are amazing! :hugs: :heart_eyes:

**Comment by samsonasik** [comment]
Bumped to Rector 2.0 🎉

**Comment by kevin-appelt** [comment]
Would be great to see this released to be able to update phpstan and rector :)

**Pull request merged**
