### PR TITLE
feat: resolve usage of BackendUtility::viewOnClick

### PR DESCRIPTION
**Pull request by helsner**
Resolves: #2586

### CODE REVIEW

**Comment by helsner** [comment]
This was a bit more complex for me, but i tried.
I don't really like the chaining of the methods, but could not think of another way.
Also the check for phpstan will fail because i did not manage to resolve the arg "$switchFocus" and provide it properly to the method as array.

I added the output styles, as the result does not fully work, but is a preparation for the further attribute handling.

**Comment by helsner** [comment]
ok, i guess i got it 👌

**Comment by sabbelasichon** [comment]
@helsner Looks promising. What has to be done manually afterwards in which situation? I am not sure if we should already rewrite this one or we should move it to v12.0 or make it optional for those who know about it? Probably both of us ;-)

**Comment by helsner** [comment]
I don't know a 100%. It depends on the individual use case.
But i guess we could make it optional for us and others.

**Comment by sabbelasichon** [comment]
Could you remove it from the config, i am going to ship it asap

**Comment by sabbelasichon** [comment]
I have done it.

**Pull request merged**
