### PR TITLE
[TASK] Add typo3-testingframework executeFrontendRequest rename

### PR DESCRIPTION
**Pull request by DanielSiepmann**

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
I didn't check whether this is v7 related.

**Comment by oliverklee** [comment]
Would it work (and make sense) to cover this with a test?

**Comment by DanielSiepmann** [comment]
Sure. I just had to configure this during one project update and this PR is just to share this.

Last time I opened an issue to share my setup as the file didn't exist.
Feel free to improve, add tests, etc.

**Comment by simonschaufi** [comment]
This is the changing commit: https://github.com/TYPO3/testing-framework/commit/d62c872d048015a3faee0b7b909302b8d3e54930 and it was changed with [6.5.0](https://github.com/TYPO3/testing-framework/releases/tag/6.5.0)

**Pull request merged**
