### PR TITLE
Allow refactoring TCA section 'ctrl' using AbstractTcaRector and rework types-refactoring a bit

### PR DESCRIPTION
**Pull request by MK-42**

### CODE REVIEW

**Comment by MK-42** [comment]
@sabbelasichon CI is not triggered anymore - is that on purpose, do do I need to adapt something here?

**Comment by MK-42** [comment]
ready for review.
I'm skimming through some of the tca rectors to find blindspots that are not yet covered with the new structure. I would then write some .rst about the whole thing - i think that might help other devs to chime in here.

are there any other not-yet-implemented tca migrations that i should tackle along the way?

**Comment by sabbelasichon** [comment]
Thanks. No, not i am aware of. I have labeled all of them with TCA or TCA Core. We should be done for now.

**Comment by sabbelasichon** [comment]
@MK-42 Thanks a lot. Looks clean. It is getting brighter and brighter

**Pull request merged**
