### PR TITLE
[TASK] Use validate instead of getValidationResults on Argument & Arguments (#1059)

### PR DESCRIPTION
**Pull request by tomasnorre**
Resolves: #1059

### CODE REVIEW

**Comment by tomasnorre** [comment]
Hi @sabbelasichon 
I know you said tests and stubs wasn't needed, but felt safer this way to ensure that my change was actually working.
Happy to get some feedback.

**Comment by sabbelasichon** [comment]
@tomasnorre I would prefer the simple configurable rule, but i will give feedback for this one nevertheless.

**Comment by tomasnorre** [comment]
Like this in the `config/v9/typo3-93.php` 

```php
    $services->set(RenameMethodRector::class)
        ->call('configure', [[
            RenameMethodRector::METHOD_CALL_RENAMES => inline_value_objects([
                new MethodCallRename(
                    Argument::class,
                    'getValidationResults',
                    'validate'
                ),
            ]),
        ]]);

    $services->set(RenameMethodRector::class)
        ->call('configure', [[
            RenameMethodRector::METHOD_CALL_RENAMES => inline_value_objects([
                new MethodCallRename(
                    Arguments::class,
                    'getValidationResults',
                    'validate'
                ),
            ]),
        ]]);
```

And remove the rest of the things I've done? Not sure how to validate it though, and the output todo you had in the issue description. 

> The only thing that´s left is how to communicate that typo3-rector is doing this change for you.

**Comment by sabbelasichon** [comment]
@tomasnorre I am gonna close this one. In favour of this one #1634. It is the same as you suggested. And yes, the only thing that´s left, is how to communicate this. I have to take care of it. Will open an issue for that.

**Pull request closed without merging**
